<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Yams! Yams! Yams!</title>
</head>
<body>
    <h1 class="text-lg-center mb-5">Le Yams c'est génial !!!</h1>
    <div class="container">
        <div class="col-6 mx-auto">
            <h2 class="text-lg-center mb-5">Nombre d'essais : <?=isset($_POST["tries"]) ? htmlspecialchars($_POST["tries"]) : 100 ?></h2>
            <table class="table table-dark table-striped">
                <thead>
                    <tr>
                        <th scope="col">Combinaison</th>
                        <th scope="col">Nombre d'occurrences</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($results as $resultName => $value) : ?>
                    <tr>
                        <td><?=$resultName ?></td>
                        <td><?=$value?></td>
                    </tr>
                    <?php endforeach ;?>
                </tbody>
            </table>
            <form action="" method="post">
                <div class="col-auto">
                    <input name="tries" class="form-control form-control-lg" type="text" placeholder="Nouveau nombre d'essais" aria-label="Nouveau nombre d'essaies">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary btn-lg mx-auto mt-5">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>